# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questionn',
            new_name='question',
        ),
    ]
